name: cloudbuild

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/1366473574/locations/global/workloadIdentityPools/githubactionspool/providers/github'
          service_account: 'githubactions@clean-mason-391409.iam.gserviceaccount.com'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: gcr.io/${{ env.PROJECT_ID }}/poc-ikea-service

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/poc-ikea-service
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
       #   service_account_key: ${{ secrets.GCP_SA_KEY }}
          image: gcr.io/${{ env.PROJECT_ID }}/poc-ikea-service
          service: POChost
          region: us-central1
          platform: managed
          # Add any additional flags or configurations as needed
    env:
      PROJECT_ID: clean-mason-391409
