name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  PROJECT_ID: clean-mason-391409 # TODO: update Google Cloud project id
  GAR_LOCATION: europe-central2 (Warsaw) # TODO: update Artifact Registry location
  SERVICE: europe-central2-docker.pkg.dev/clean-mason-391409/pochost # TODO: update Cloud Run service name
  REGION: europe-central2 # TODO: update Cloud Run service region

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: Add IAM policy binding
        run: |
          gcloud iam service-accounts add-iam-policy-binding terraform-sa@clean-mason-391409.iam.gserviceaccount.com \
            --role=roles/iam.workloadIdentityUser \
            --member="principal://iam.googleapis.com/projects/clean-mason-391409/locations/global/workloadIdentityPools/githubactionspool/subject/google.subject"

      # Rest of the workflow steps...
