name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: clean-mason-391409 # TODO: update Google Cloud project id
  SERVICE: pochost # TODO: update Cloud Run service name
  REGION: europe-west2 # TODO: update Cloud Run service region

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} ./ --project ${{ env.PROJECT_ID }}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} --quiet --platform managed --region ${{ env.REGION }} --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} --project ${{ env.PROJECT_ID }}
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
