name: CodeQL Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript

      - name: Publish CodeQL results
        uses: actions/upload-artifact@v2
        with:
          name: CodeQL Results
          path: codeql-results
