name: CodeQL Pipeline
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run your CodeQL analysis
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          languages: javascript

      # Publish artifacts
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CodeQL results
          path: codeql-results
