name: Deploy Cloud Run

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  PROJECT_ID: clean-mason-391409
  SERVICE: pochost
  REGION: europe-west2
  SONAR_PROJECT_KEY: POChost
  SONAR_ORGANIZATION: poc-ikea

jobs:
  DeployCloudRun:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and Generate ESLint report
        run: |
          npm ci
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7
          npx eslint .
            --config .eslintrc.js
            --ext .js,.jsx,.ts,.tsx
            --format json
            --output-file eslint_report.json
        continue-on-error:  true    

      - name: Run lint
        run: npx eslint --format=json . > eslint-report.json
        continue-on-error: true  # Continue the build even on ESLint errors

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/1366473574/locations/global/workloadIdentityPools/githubactionspool/providers/github'
          service_account: 'terraform-sa@clean-mason-391409.iam.gserviceaccount.com'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        with:
          projectBaseDir: src
          args: >
            -Dsonar.organization=poc-ikea
            -Dsonar.projectKey=POChost

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} ./ --project ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          image: gcr.io/${{ env.PROJECT_ID }}/pochost
          service: pochost
          region: europe-west2
          platform: managed
          # Add any additional flags or configurations as needed by you.

      - name: Upload ESLint report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ESLint Report
          path: eslint_report.json

    env:
      PROJECT_ID: clean-mason-391409
