name: Pull Request Job

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  PROJECT_ID: clean-mason-391409
  SERVICE: pochost
  REGION: europe-west2
  SONAR_PROJECT_KEY: POChost
  SONAR_ORGANIZATION: poc-ikea

jobs:
  PRRun:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7
          npx eslint .
            --config .eslintrc.js
            --ext .js,.jsx,.ts,.tsx
            --format @microsoft/eslint-formatter-sarif
            --output-file eslint-results.sarif

      - name: Run lint
        run: npm run lint
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        with:
          projectBaseDir: src
          args: >
           -Dsonar.organization=poc-ikea
           -Dsonar.projectKey=POChost
        
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     
      - name: Upload ESLint report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ESLint Report
          path: eslint-results.sarif
    env:
      PROJECT_ID: clean-mason-391409
