name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '380.0.0'
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Build and deploy to Google Cloud Storage
        run: |
          # Replace 'project-folder-path' with the path to the project folder within the GitHub Actions workspace
          gsutil -m cp -r ${{ github.workspace }} gs://microfrontendpoc/
