name: ESLint-Test

on:
  push:
  schedule:
    - cron: '45 15 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run npm install
        run: npm install

      - name: Run ESLint
        run: npx eslint build docs lib script spec-main \
             --format=node_modules/@microsoft/eslint-formatter-sarif/sarif.js \
             --output-file=results.sarif || true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/${{ github.run_id }}/eslint-results.sarif
          wait-for-processing: true

